(function(){
  document.documentElement.classList.add('js');
  var MEASUREMENT_ID='G-08GTRQQTFK';
  function track(action,label){ if(typeof window.gtag==='function'){ window.gtag('event',action,{event_category:'lead_generation',event_label:label||'website',send_to:MEASUREMENT_ID}); } }
  function sanitize(v){ return String(v||'').replace(/\s+/g,' ').trim(); }
  function initMenu(){ var btn=document.querySelector('.menu-toggle'); var menu=document.getElementById('mobile-menu'); if(!btn||!menu)return; btn.addEventListener('click',function(){ var open=btn.getAttribute('aria-expanded')==='true'; btn.setAttribute('aria-expanded',String(!open)); menu.classList.toggle('is-open',!open); }); menu.querySelectorAll('a').forEach(function(a){ a.addEventListener('click',function(){ btn.setAttribute('aria-expanded','false'); menu.classList.remove('is-open'); }); }); }
  function buildMessage(form){ var data=new FormData(form); return encodeURIComponent(['New enquiry from website','Page: '+location.pathname,'Name: '+sanitize(data.get('full_name')),'Phone: '+sanitize(data.get('phone')),'City: '+sanitize(data.get('city')),'Buyer type: '+sanitize(data.get('buyer_type')),'Product / service: '+sanitize(data.get('requirement_type')),'Size / quantity: '+sanitize(data.get('size_quantity')),'Preferred contact: '+sanitize(data.get('preferred_contact_method')),'Message: '+sanitize(data.get('message'))].join('\n')); }
  function initForms(){ document.querySelectorAll('form.js-quote-form').forEach(function(form){ form.addEventListener('submit',function(e){ e.preventDefault(); if(!form.reportValidity())return; track('generate_lead',form.dataset.context||location.pathname); window.open('https://wa.me/919426391608?text='+buildMessage(form),'_blank','noopener'); form.reset(); }); }); }
  function initTracking(){ document.querySelectorAll('a[href^="tel:"]').forEach(function(a){ a.addEventListener('click',function(){ track('phone_call_click',sanitize(a.textContent)||a.href); }); }); document.querySelectorAll('a[href*="wa.me"]').forEach(function(a){ a.addEventListener('click',function(){ track('whatsapp_click',sanitize(a.textContent)||a.href); }); }); }
  function initReveal(){ var els=[].slice.call(document.querySelectorAll('.reveal')); if(!('IntersectionObserver' in window)){ return; } els.forEach(function(el){ el.style.opacity='0'; el.style.transform='translateY(20px)'; el.style.transition='opacity .65s cubic-bezier(.2,.7,.2,1), transform .65s cubic-bezier(.2,.7,.2,1)'; }); var io=new IntersectionObserver(function(entries){ entries.forEach(function(entry){ if(entry.isIntersecting){ entry.target.style.opacity='1'; entry.target.style.transform='none'; io.unobserve(entry.target); } }); },{threshold:.12}); els.forEach(function(el){ io.observe(el); }); setTimeout(function(){ els.forEach(function(el){ el.style.opacity='1'; el.style.transform='none'; }); },2500); }
  function initPreloader(){ if(matchMedia('(prefers-reduced-motion: reduce)').matches || sessionStorage.getItem('sk-preloader-seen')) return; sessionStorage.setItem('sk-preloader-seen','1'); var el=document.createElement('div'); el.className='preloader'; el.innerHTML='<svg width="360" height="220" viewBox="0 0 600 360" fill="none"><path pathLength="100" d="M80 290 L80 130 L250 130 L250 240 L430 240 L430 110 L535 110" stroke="#1c3d5a" stroke-width="26" stroke-linecap="butt" fill="none" style="stroke-dasharray:100;stroke-dashoffset:100;animation:sk-draw 1.1s ease-out forwards"></path><path d="M80 290 L80 130 L250 130 L250 240 L430 240 L430 110 L535 110" stroke="#86c2f0" stroke-width="9" fill="none" stroke-linecap="round" stroke-dasharray="6 28" style="animation:sk-flow .9s linear 1s infinite"></path></svg><div class="preloader-text">Assembling the pipeline</div>'; document.body.appendChild(el); setTimeout(function(){ el.classList.add('is-hidden'); setTimeout(function(){ el.remove(); },500); },1350); }
  function initVideo(){ document.querySelectorAll('video').forEach(function(v){ v.muted=true; var p=v.play(); if(p&&p.catch)p.catch(function(){}); }); }
  document.addEventListener('DOMContentLoaded',function(){ initPreloader(); initMenu(); initForms(); initTracking(); initReveal(); initVideo(); var year=document.getElementById('year'); if(year)year.textContent=new Date().getFullYear(); });
})();
